server:
  port: 10010

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

spring:
  application:
    name: gateway

zuul:
  routes:
    user-service:
      path: /user/**
      serviceId: user-service
      strip-prefix: false

  ignored-services: consumer-service

#    user-service: /user/**
#     user-service: /user-service/**
#    caozheng:
#      path: /user-service/**
#      serviceId: user-service

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000

ribbon:
  ConnectionTimeout: 500   # ribbon超时时长，真实值是(read+connect)*2 ,必须小于hystrix延时时长
  ReadTimeout: 2000
  maxAutoRetriesNextServer: 0  #不重试


