server:
  port: 8088

spring:
  application:
    name: consumer-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
    registry-fetch-interval-seconds: 3
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

feign:
  hystrix:
    enabled: true

ribbon:
  ConnectionTimeOut: 500
  ReadTimeOut: 2000

user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #ribbon 负载均衡策略(选择随机)


#histrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000
logging:
  level:
    cn.itcast: debug
